import { SLICE_NAME } from '@config/type';

export const LOGIN = SLICE_NAME.AUTHENTICATION + 'LOGIN';

export const SIGNUP = SLICE_NAME.AUTHENTICATION + 'SIGNUP';

export const FORGOT_PASSWORD = SLICE_NAME.AUTHENTICATION + 'FORGOT_PASSWORD';
